### PR TITLE
MotherCell Updates

### PR DESCRIPTION
**Pull request by NatsuTheGreat**

### CODE REVIEW

**Comment by Barbosik** [comment]
this change will leads to more lags:
1) check inside loop is slower than check outside loop;
2) update MotherCell on each tick will leads to lags

Also, viruses cannot eat each other. There is even no collision check for such case.

**Comment by NatsuTheGreat** [comment]
A mothercell CAN eat a virus :)

**Comment by Barbosik** [comment]
for what? Is it possible on vanilla servers?

**Comment by NatsuTheGreat** [comment]
Yes, it is possible for a mothercell to eat a virus in agar.io. With my update, that is possible too.

**Comment by SimonOrJ** [comment]
Possible indeed

**Pull request closed without merging**
