### PR TITLE
New spectacor mode

### PR DESCRIPTION
**Pull request by lulzyyy**
By pressing Q - Free Roam
By pressing W - spectate next player from client list (alive) until his death
By pressing Space - spectate the largest player

tested, works fine. but needs optimization I think

### CODE REVIEW

**Comment by NatsuTheGreat** [comment]
You don't need space, Q will switch between Free-Roam and Largest player.

**Comment by lulzyyy** [comment]
But it's more understandable.

**Comment by NatsuTheGreat** [comment]
What do you mean? Everyone is used to switching with Q. And that adds extra code.

**Comment by lulzyyy** [comment]
Let Barbosik decide. It's just a suggestion.

**Comment by NatsuTheGreat** [comment]
I was just making a point. :P

**Comment by Barbosik** [comment]
it seems that some change is missing from your pull request.

I added this feature, but in a slightly different way.
New spectate mode works the same as previously. But now you can lock current player with Space key. 

If you want to switch on next player - just press Space again. 
Pressing Q will reset player lock to largest player if lock was activated, otherwise Q works in usual way - just toggles freeRoam/largest mode.

Locked player is highlighted on leaderboard. 
So, if you pressed Space for the first time, the largest player will be highlighted on leaderboard. It means that largest player is locked and spectate will not switch automatically. With next pressing on Space you can switch to the next player.

**Comment by lulzyyy** [comment]
OK, Thanks!

**Comment by Barbosik** [comment]
some note, highlight on leaderboard will works good with protocol 6 (vanilla client), for older protocol it will works only if the client understand late protocol 5 modification (uisng 0/1 instead cell id). Unfortunately, for older protocol there is no way to highlight the item on leaderboard from spectate mode. But spectate feature will works ok. These clients just cannot highlight the item on the leaderboard.

**Comment by lulzyyy** [comment]
I noticed it but it's a little important detail

**Comment by lulzyyy** [comment]
I noticed also when I join server and click spectate mode, I spectate the largest players (it's ok) but then I must press Space several times to switch to another player.

**Comment by Barbosik** [comment]
it's protection to not allow change spectate mode too often. There is need to wait 1 sec before pressing space. Because it may leads to server lags if you change spectate too often.

**Comment by lulzyyy** [comment]
Yea I know, but it should be activated after the first press of the space bar

**Comment by Barbosik** [comment]
no, there is need for some pause before first press on the space bar. Because server needs to send update info. For largest player, update info consists a lot of data. So, there is need to make some pause to let the server ability to send the data and relax.

**Comment by lulzyyy** [comment]
It's ok. I appreciate your hard work on this project and that you spend a lot of time on it. Maybe now you could try to optimize the game client?

**Comment by Barbosik** [comment]
I already written my own highly optimized client, it can render 5000-20000 cells on the screen with no lag. You can found it's screenshot in the readme

**Comment by lulzyyy** [comment]
DAMN NICE :) Where is the code?

**Comment by Dramex** [comment]
@Barbosik i have a custom client, servers with a alot of visitors, 
i want to buy a copy from that client
contact me at ea@ea.sa

**Comment by lulzyyy** [comment]
LOL

**Comment by lulzyyy** [comment]
BTW. @Barbosik I added serverTracker to my http://c0nsume.me private server list. So now, every MultiOgar server with 'serverTracker' set to 1 wil appear on my server list :dancer: 

sry it was my last post in this topic.

**Comment by Influxx** [comment]
@Barbosik any chance of the client being released?

**Comment by Barbosik** [comment]
**lulzyyy**: there is a new message to get server statistics (server name, game mode and player count). You can use it in your client to show server info (instead of request to server stat http port, because it may not be started).
When your client is connected, just send message 254 and server will respond with message 254. This message from server contains UTF8 string with JSON with server info:
name: server name
mode: current game mode
uptime: server uptime in seconds
update: update time in milliseconds (can be used for lag indicator, if > 40 it means lags)
playersTotal: current count of players on the server
playersAlive: current count of players joined to the game
playersSpect: current count of players in spectate mode
playersLimit: maximum count of players allowed on the server

**Comment by lulzyyy** [comment]
Ok ;) But I need the code to read this message, I'm tired now I can't think :P Then I'm implementhing it today

**Comment by lulzyyy** [comment]
Btw. Please add customcfg.ini or something. Because I have to rewrite some values after every update. Thanks.

**Comment by Barbosik** [comment]
the format of message is very easy: first byte is 254 (message id) and then UTF8 string with JSON, that's it :)

**Comment by lulzyyy** [comment]
ok :)

**Comment by Barbosik** [comment]
stats port is not disabled, but it can be configured on different ports. So, you never know on which port it's running. This is reason why stats server mostly useless, because no one know which port is used for stat.
So, I added message to allow client to get this info in easy way with no need for another connection.

**Comment by Influxx** [comment]
I like the idea of having a `custom-config.ini` too, it could override `gameserver.ini`and we could add this file to `.gitignore` to stay up to date with the latest commits more easily. 

Maybe rename `gameserver.ini` to `config.ini` because it's a config file.

**Comment by Barbosik** [comment]
you can just remove gameserver.ini. It added to git just as example.
If you remove it, server will create new one with default values

**Comment by Barbosik** [comment]
actually you can just run the server in the folder MultiOgar instead of MultiOgar/src:
```
sudo node src/index.js
```

it will create your own gameserver.ini in the folder MultiOgar, which will not be overwritten.

But I added gameserver.ini to .gitignore. So, you can execute git pull, it will not change your src/gameserver.ini

**Comment by lulzyyy** [comment]
Server stats are working now with my client :)

**Pull request closed without merging**
