### PR TITLE
Add config option to enable uws

### LINKED ISSUE #158: Support for the uws module
I would like to see `uws` support as it could allow many more clients to connect to multiogar while using less system resources.

### PR DESCRIPTION
**Pull request by henopied**
This enables support for `uws` in the `gameserver.ini` configuration file. Closes #158

### CODE REVIEW

**Comment by Barbosik** [comment]
1) it's not good idea to commit code formatting with some code change. Because it's too hard to understand what really were changed
2) did you noticed that sendPacket code were changed? and this change was removed in your pool request

**Comment by NatsuTheGreat** [comment]
>1) it's not good idea to commit code formatting with some code change. Because it's too hard to understand what really were changed

Pretty sure Github does this crap by itself,

**Comment by henopied** [comment]
@Barbosik I'm sorry but my text editor decided to format this on its own. and the latest sendPacket code wouldn't work with uws because `_socket` does not have a `writable` property in uws.

**Comment by Barbosik** [comment]
then there is need to find how this property is named in uws and how to get it. Because removing such check will leads to lags

**Comment by alexhultman** [comment]
You shouldn't use writable in the check, that's not needed and I cannot see any reference of its usage in the documentation. Any net.Socket is always writable, you only need to check the readyState. If you want to hinder any accumulation of unsent messages you need to use the send callback:

ws.send(buffer, {binary: true}, callback);

This callback is called when the buffer has been consumed. Use that to check if what you sent got consumed before you send anything more.

**Comment by Barbosik** [comment]
@alexhultman: this check was added to check if socket is in closing state. It allows to reduce send errors. Without this check the log is spammed with errors, such as 'This socket has been ended by the other party', 'This socket is closed.' and other.

For example:
```
[ERROR][03:20:18] [<IP>:58400] Error: This socket is closed.
    at Socket._write (net.js:635:19)
    at doWrite (_stream_writable.js:223:10)
    at writeOrBuffer (_stream_writable.js:213:5)
    at Socket.Writable.write (_stream_writable.js:180:11)
    at Socket.write (net.js:613:40)
<...>
```

It also allows to check if the connection is closed before build packet (when close event still not emited)

**Comment by alexhultman** [comment]
That's really strange how you manage to get a conflicting report from readyState (OPEN), yet have a closed net.Socket. In any case, you don't need to check this in uws - if readyState is OPEN the socket is guaranteed to be writable, so you could change that check to something like:

if (uws_is_the_ws_module || writable_check_here) {

}

**Comment by Barbosik** [comment]
@alexhultman: it's bad if closed connection is writable, because it will leads to useless cpu load to build packet for closed client. Each client eats some significant cpu time, because it needs to lookup for visible cells, build packet, etc. It's better to skip these actions on close connection as soon as posible

**Comment by alexhultman** [comment]
Yes, but my point is, in uws you will never get readyState == OPEN on a closed socket. If you get readyState == OPEN, the socket is open.

**Comment by alexhultman** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#Ready_state_constants

readyState == OPEN should always mean the socket is writable. How you manage to get ws to report the socket to be OPEN, yet the net.Socket is closed is probably due to something strange in the usage.

**Comment by Barbosik** [comment]
ok, it's good solution

**Comment by Barbosik** [comment]
@alexhultman: How you manage to get ws to report the socket to be OPEN, yet the net.Socket is closed is probably due to something strange in the usage.

it's just ws implementation. It reports readyState == OPEN, but attempt to write fails. Usually it doesn't happens on dev environment. But it happens very often when there are a lot of real connections. 
The bad thing is that it fails inside ws code for read operation, and I cannot prevent it:
```
[ERROR][08:41:51] [<IP>:52823] Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
```

**Comment by henopied** [comment]
@alexhultman @Barbosik  This almost seems like a bug with ws itself. Should I check if we are using ws and if _socket is writable? That would seem to fix this issue.

**Comment by alexhultman** [comment]
Yeah just ignore that check with uws

**Comment by henopied** [comment]
I believe I have fixed this issue.

**Comment by henopied** [comment]
@Barbosik @alexhultman Might there be anything else that needs to be changed before this can be merged?

**Comment by alexhultman** [comment]
@henopied That's awesome, now I can get it to work :). However I think the configuration is broken, I wasn't able to swap to uws via the config but had to hardcode the require. You can check what implementation is running by opening developer tools in Chrome and Network and check the response headers of the WebSocket connection. It will say Server: uWebSockets if uws is running.

**Comment by alexhultman** [comment]
My bad, it works. I edited the wrong gameserver.ini...

**Comment by SimonOrJ** [comment]
I am developing something random using `uws` on Windows.  It seems that `uws` only works on Node v6.3.0 and above.

**Comment by henopied** [comment]
@SimonOrJ Luckily uws has an almost identical api to ws so you can swap them easily.

**Comment by alexhultman** [comment]
Merge? The reported issue is not caused by this PR but rather by the _socket getter failing on closed sockets in uws. This will be fixed in uws itself so nothing about this PR.

**Comment by Barbosik** [comment]
there is an issue with installation. I cannot install uws.

**Comment by alexhultman** [comment]
What issue?

**Comment by Barbosik** [comment]
I tried to install it on windows machine, if I understand correctly, it requires npm package windows-build-tools. When I executed `npm install windows-build-tools` it starts to download a bunch of megabytes with different exe, msi, etc. After 30 minutes of installation it just hung.

**Comment by alexhultman** [comment]
These windows-build-tools install failures are Microsoft's problem, it's their broken package. You don't need it, it's just optional. npm install uws is without any dependencies but it can recompile using windows-build-tools (but this piece of shit package never works).

**Comment by henopied** [comment]
Btw, as soon as `_socket#writable` is added to uws it will be used as my pr checks if it is defined not if we are using uws.

**Comment by SimonOrJ** [comment]
If you use Node version 6.3.0 and higher, then uws will work without having to go through compiling issues.  It doesn't work with windows-build-tools anymore.

**Comment by alexhultman** [comment]
There's now 0.7.9 which fixes #219

**Comment by alexhultman** [comment]
Btw, if you make uws default I can link to this project from front page.

**Comment by Barbosik** [comment]
merged

**Pull request closed without merging**
