### PR TITLE
Fix some issues

### PR DESCRIPTION
**Pull request by NatsuTheGreat**

### CODE REVIEW

**Comment by NatsuTheGreat** [comment]
Finally got it to work. I really apologize for the other useless pull requests.

**Comment by NatsuTheGreat** [comment]
#274 Fixed.

**Comment by NatsuTheGreat** [comment]
@Barbosik Is this good to go or do I need to fix something?

**Comment by Barbosik** [comment]
>>Partially fix cells flying through cells

This code will works slower, and doesn't provide any benefit, it just using additional loop for update.
Current version utilize existing loop so it will works faster. Split frequency doesn't affect it at all, because all this code works between split commands.

**Comment by NatsuTheGreat** [comment]
>This code will works slower, and doesn't provide any benefit, it just using additional loop for update.
Current version utilize existing loop so it will works faster. Split frequency doesn't affect it at all, because all this code works between split commands.

I agree it may work slower, but on my mod, that fixed cells flying through cells for the most part.

>this is bad idea to add something which can be handled in different place into canEat function. Because this function can be called thousands of times per second and should be as fast as possible.
I think the better place for this behavior is onEat function

I have placed that in canEat because it will match vanilla, ejected cells will fly through viruses if the max virus amount is reached. If I place it in onEat the virus will eat the ejected cell without gaining mass. And what really slows is down that bad? :/

>Why check for pos==null was removed?
And it's better to use isMoving instead of boostDistance.

That was removed because pos is already defined at the top of the function. There is no reason to null check it. And I'll fix that.

**Comment by Barbosik** [comment]
>>I have placed that in canEat because it will match vanilla, ejected cells will fly through viruses if the max virus amount is reached.

I didn't played latest vanilla, but previously it worked in different way on vanilla - virus just eat ejected mass, but doesn't eject new virus

**Comment by NatsuTheGreat** [comment]
I have never actually seen this behavior ever on vanilla.
Please check [this video](https://youtu.be/aBWk3csDDEc?t=324) and see what I mean. 
He reaches the max amount of viruses, and they no longer eat the ejected cells.
[This time frame](https://youtu.be/aBWk3csDDEc?t=354) Shows the same. They reach the maximum amount of viruses, and the viruses no longer eat the ejected cells whatsoever. This is before the protocol change as you can tell by the leaderboard and score at bottom left.

**Comment by NatsuTheGreat** [comment]
@Barbosik Is this okay to merge now?

**Comment by NatsuTheGreat** [comment]
Hello @Barbosik?

**Pull request closed without merging**
