### PR TITLE
.

### PR DESCRIPTION
**Pull request by AlexHGaming**

### CODE REVIEW

**Comment by ItzLevvie** [comment]
Close? @AlexHGaming

**Comment by Megabyte918** [comment]
@AlexHGaming close?

**Comment by AlexandriteErikParacelsus** [comment]
@AlexHGaming close?

**Comment by raphyjb** [comment]
Please update skins, since on agario the private server doesnt work, i tryed help u guys 
http://pastebin.com/LQqiwf1Z
this is for C0nsume.me website all their skins

**Comment by ItzLevvie** [comment]
@AlexHGaming Close please?

**Pull request closed without merging**
