### PR TITLE
​

### PR DESCRIPTION
**Pull request by ItzLevvie**
​

### CODE REVIEW

**Comment by ItzLevvie** [comment]
"why you make changes in the commented section?" - @F0RIS

The reason why this "custom skins" code was commented out was because people could use some dirty skins which can be offensive to other people (like. a skin with girls boobs or their private parts.)

"this commented section for users' handmade skins?"

Yes, when ```+ ".png"``` isn't there, you'll have to type |I48HJEd.png| in the name box to get a custom skin, but when it is implemented you can do |I48HJEd| (without the .png, this will save you more nickname space) to get a custom skin.

**Comment by Barbosik** [comment]
**F0RIS**: it's dangerous code, because someone can upload picture with virus or some dirty skins and it will be shown to all players. You can uncomment it and use for private servers, but it's strongly not recommended for public available servers. It can make players with not protected clients vulnerable.

**Comment by F0RIS** [comment]
@ItzLevvie Thanks for explanation! :) I didn't even know that this server have such feature. Interesting)

**Comment by F0RIS** [comment]
What about making switcher for this feature in config file?

**Pull request merged**
