### PR TITLE
Ban Commands + Remove serverIpBanList Toggle + Ignore "src/blacklist.txt"

### PR DESCRIPTION
**Pull request by SimonOrJ**
* Using `> ban` (without any argument) caused error.  This patches it using a null check.
* Banning with an IP address now checks for a valid IPv4 address.
* Added `banlist` command.
* Made banning more clear upon ban.

The `serverIpBanList` toggle seemed redundant.

Added `src/blacklist.txt` to avoid prevent other people forking/committing this project from revealing random IP addresses.

### CODE REVIEW

**Comment by SimonOrJ** [comment]
I current have no idea.

I opened a test Ogar server open at the same server, port 24279.  I'm thinking of leaving it open for some time then joining the server with multiple instances of Agario.

I believe the lag might have to do with the connection more than the game engine.  I am not entirely sure yet.

**Comment by Barbosik** [comment]
if you opened Ogar on the same server it may be the reason of lags, because it eats a lot of memory and cpu. So, server will not be able to run smoothly.

**Comment by SimonOrJ** [comment]
There's generally only one instance of Ogar on the server.  I opened a second one on port 24279 just for lag testing.

The VPSthis server is running on is dedicated to running Ogar.

**Comment by Barbosik** [comment]
**SimonOrJ**: please apply current version to your server, it will fix split behavior, spectate bug and should improve performance

**Pull request merged**
