### PR TITLE
Patato

### PR DESCRIPTION
**Pull request by Fantasy-Agario**

### CODE REVIEW

**Comment by NatsuTheGreat** [comment]
FFS How gullible are you.................

**Comment by Megabyte918** [comment]
@Fantasy-Agario you mind closing this? why was this even open in the first place? lol

**Comment by firelightning13** [comment]
@Barbosik

**Comment by MastaCoder** [comment]
what the heck is this commit.

**Comment by AlexandriteErikParacelsus** [comment]
@Fantasy-Agario wtf is this why all of these comments are here

**Comment by AlexandriteErikParacelsus** [comment]
@Fantasy-Agario can you close

**Comment by MastaCoder** [comment]
holy crap can someone close this?

**Comment by firelightning13** [comment]
@Fantasy-Agario Can you close this? This is so annoying!

**Pull request closed without merging**
