### PR TITLE
Add Skin Command

### PR DESCRIPTION
**Pull request by MastaCoder**
Allow the changing of skin of a cell through a command. Pretty simple command, works like name, simply changes the player's skin instead of name.

### CODE REVIEW

**Comment by Barbosik** [comment]
there is function GameServer.getPlayerById. I think it's better to use this function instead of iterating through all players

**Comment by MastaCoder** [comment]
@Barbosik For some reason the new function seems to be causing some issues. The following code added to the cell does change the cells skin, but for some reason an issue is happening on the server where not all the cells get the skin. So when I type in skin for a cell, after 1 split the skin isn't there, the 2nd split the skin is there. If you merge the cell, the same thing happens again which is weird. Every first split has no skin, hitting a virus, the center piece has no skin.

```skin: function (gameServer, args) {
        console.log(args);
        if (!args || args.length < 2) {
            Logger.warn("Please specify a valid player ID!");
            return;
        }
        var id = parseInt(args[1]);
        if (isNaN(id)) {
            Logger.warn("Please specify a valid player ID!");
            return;
        }
        var skin = args[2];
        var player = gameServer.getPlayerById(id);
        if (player == null) {
            Logger.warn("Player with id=" + id + " not found!");
            return;
        }
        Logger.print("Player \"" + player.getFriendlyName() + "\"'s skin is changed to " + skin);
        player.setSkin(skin);
    },```

**Comment by NatsuTheGreat** [comment]
Just do
 ```
Code here
 ```

**Comment by NatsuTheGreat** [comment]
```
skin: function (gameServer, args) { console.log(args); if (!args || args.length < 2) { Logger.warn("Please specify a valid player ID!"); return; } var id = parseInt(args[1]); if (isNaN(id)) { Logger.warn("Please specify a valid player ID!"); return; } var skin = args[2]; var player = gameServer.getPlayerById(id); if (player == null) { Logger.warn("Player with id=" + id + " not found!"); return; } Logger.print("Player \"" + player.getFriendlyName() + "\"'s skin is changed to " + skin); player.setSkin(skin); },
```

**Comment by SimonOrJ** [comment]
@MastaCoder Use:

&grave;&grave;&grave;js
<code here>
&grave;&grave;&grave;

**Comment by MastaCoder** [comment]
Got it :page_facing_up:

**Comment by Barbosik** [comment]
@MastaCoder: the issue here is because you cannot change skin if the cell is already exists. If you doing it for existing cell, it will display different skin for different players. And player will not see any change until their cell is alive. You can change skin properly when player is not joined to the game.

**Comment by NatsuTheGreat** [comment]
It's a player command right? You could just set your skin in the name box.

**Comment by Barbosik** [comment]
@NatsuTheGreat: no, he added server console command. The player command '/skin' is already implemented some time ago

**Comment by NatsuTheGreat** [comment]
Yeah I was talking about "/skin" :P

**Comment by Barbosik** [comment]
@NatsuTheGreat: this PR adds the same command for server console

**Comment by NatsuTheGreat** [comment]
Isn't "/skin" only for the player using it and "skin" for the pID that matches the ID argument?

**Comment by Barbosik** [comment]
@NatsuTheGreat: server console command has no player, it's executed by server admin, so there is need for playerId to specify exact player which will be affected with the command

**Comment by NatsuTheGreat** [comment]
>var id = parseInt(split[1]);
if (client.pID == id) {

The console command here uses pID

**Comment by Barbosik** [comment]
I added it, with a small fixes

**Comment by MastaCoder** [comment]
@Barbosik The /skin command only works if the cell is not in game right?

**Comment by Barbosik** [comment]
yes. Actually the skin is changed. But if this cell is already on your screen, you will not see any change. Because skin is sent on the first cell update only. So, if it already present on your skin, you will not see skin change.

**Comment by MastaCoder** [comment]
@Barbosik Yeah I see what you're talking about. Some client changes could get that to work, I'll see what I can do on my client. :+1:

**Pull request closed without merging**
