### PR TITLE
send Admin information with message

### PR DESCRIPTION
**Pull request by lulzyyy**

### CODE REVIEW

**Comment by MastaCoder** [comment]
Uhm.. Why is your site in the code..? Also why do you have to make 5 different commits just to add 2 lines.. Seems like someone is trying to shitcommit. lol

```if (this.sender && this.sender.clientOrigin == "http://c0nsume.me")
  	writer.writeUInt8(this.sender.isAdmin);		  	writer.writeUInt8(this.sender.isAdmin);```

**Comment by Barbosik** [comment]
for what reason chat message should contains info about admin?

**Comment by Barbosik** [comment]
I have no idea what is the reason to mark chat message for admins. 
But I added chat flag which indicates the source of message:

0x80 - message from server
0x40 - message from administrator
0x20 - message from moderator

You can use it in the client to highlight these messages. I don't know another use case for this info :)

**Comment by lulzyyy** [comment]
people asked for this aka different colour for admins...

**Pull request closed without merging**
