### PR TITLE
Update MotherCell.js

### PR DESCRIPTION
**Pull request by MastaCoder**
Give mother cells a 1/8 chance to spawn food even if the cell is at minimum size. This is better than not spawning food at all 💯

### CODE REVIEW

**Comment by MastaCoder** [comment]
Actually it's a bit broken. It spawns food and takes away from the map food.

**Comment by NatsuTheGreat** [comment]
Yes because you are reaching maxFoodAmount :P

**Comment by GhostShot3** [comment]
@NatsuTheGreat You have write acess here ?

**Comment by NatsuTheGreat** [comment]
No, I do not, @GhostShot3

**Pull request closed without merging**
