### PR TITLE
Make ejectSizeLoss more clear + Undefined Variable Fix on Exit

### PR DESCRIPTION
**Pull request by SimonOrJ**
It took me many hours to figure out what's up with ejectSizeLoss not matching up with expected results...

### CODE REVIEW

**Comment by Barbosik** [comment]
what problem exactly with ejectSizeLoss. I tested current behavior and it seems that it works as expected. Also if I remember correctly, approach which you're used in this change has issues with incorrect mass calculations...

**Comment by SimonOrJ** [comment]
The current code's mass loss amount is proportional to the current cell size.  This code makes mass loss consistent with the change of the cell's size/mass.  I thought setting size loss to 50 will make the cell lose 25 mass every time it ejects mass.  However, it actually made th ecell lose an additional 175 mass when the original size(mass) was 200(400), 275 when 300(900), 375 when 400(1600), etc...

The attached excel spreadsheet has some formulas.

[MultiOgar-SizeLoss.xlsx](https://github.com/Barbosik/MultiOgar/files/353542/MultiOgar-SizeLoss.xlsx)

**Comment by Barbosik** [comment]
I committed a little different version, it works more close to vanilla.
Now ejectSizeLoss defines ejected cell size which mass will be substracted from player cell.
It means that now ejectSize doesn't affect how much mass will be substracted from player cell.

**Comment by Barbosik** [comment]
fix for wsServer also applied

**Pull request closed without merging**
