### PR TITLE
Make a definite admin. (for clients with chats.)

### PR DESCRIPTION
**Pull request by BaumanDev**
The formatting blew up >.<

### CODE REVIEW

**Comment by NatsuTheGreat** [comment]
I can try to add the ability for multiple admins (so comment below if you'd like that)

**Comment by DTMClanDeveloper** [comment]
yes i would like it and now since u make a pull request what do i do, do i just re download multi ogar.

**Comment by NatsuTheGreat** [comment]
No not yet. Barbosik hasn't merged the pull request yet.

**Comment by NatsuTheGreat** [comment]
I'll work on multiple admin thing now.

**Comment by Barbosik** [comment]
login/logout user command were added

**Comment by ZiityV** [comment]
@Barbosik what do u type to login

**Comment by Barbosik** [comment]
it was designed to use from chat. For example "/login [password]"

**Pull request closed without merging**
