### PR TITLE
Update gameserver.ini

### PR DESCRIPTION
**Pull request by GhostShot3**

### CODE REVIEW

**Comment by firelightning13** [comment]
What is this for?

@Barbosik close?

**Comment by GhostShot3** [comment]
serverwsmodule to servermodule because have 2 modules

**Comment by firelightning13** [comment]
If you change `serverWsModule` to `servermodule`, it doesnt work that way.

**Comment by GhostShot3** [comment]
@firelightning13 Its ok,is closed

**Pull request closed without merging**
