### PR TITLE
Old agario

### PR DESCRIPTION
**Pull request by SAV-404**

### CODE REVIEW

**Comment by Agarian** [comment]
Why is this pull request still open? And what even was it's purpose? @SAV-404 I suggest you close this pull request.

**Comment by Agarian** [comment]
Seriously, will @SAV-404 close this? Maybe @Barbosik?

**Comment by Agarian** [comment]
@SAV-404 Will you PLEASE close this? Cause I'm tired of getting notifications whenever a change is made in MultiOgar-Edited.

**Comment by ItzLevvie** [comment]
Close? @SAV-404

**Comment by Agarian** [comment]
I don't think HE will. He probably thinks it's funny.

**Comment by SAV-404** [comment]
guys i'm sorry, i left it without closing it ;-;

**Pull request closed without merging**
